---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "quarterly"
    groups:
      frontend:
        patterns:
          - "*"
