---
name: Stylelint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: stylelint
        uses: actions-hub/stylelint@master
        env:
          INDENT_SPACES: 2
          PATTERN: "static/*.css"
